name: hello TestBash
run-name: ${{ github.actor }} is learning Gethub commands
on: [push]
jobs:   
  check-bats-version:
    runs-on: ubuntu-latest   
    steps:
      - run: echo "TestBash"

  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - run: cd src/webapp/api && npm install && npm run test
      
        