name: hello TestBash
run-name: ${{ github.actor }} is learning Gethub commands
on: [push]
jobs:   
  check-bats-version:
    runs-on: ubuntu-latest   
    steps:
      - run: echo "TestBash"

  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run test